services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\AMQP\RecordAMQPMetricsCommand:

  App\AMQP\Repository\AMQPQueueMetricsRepository:
    arguments:
        $vhost: '%env(AMQP_MONITORING_VHOST)%'