services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\NewRelic\JsonNewRelic:
    arguments:
        $appId: '%env(NEW_RELIC_APP_ID)%'
        $Relickey: '%env(NEW_RELIC_API_KEY)%'
        $RelicHost: '%env(NEW_RELIC_HOST)%'
     