services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\NewRelic\NewRelicAppReportingPuller:
    arguments:
        $appId: '%env(NEW_RELIC_APP_ID)%'
        $apiKey: '%env(NEW_RELIC_API_KEY)%'
        $host: '%env(NEW_RELIC_HOST)%'
     