# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    assets:
        json_manifest_path: "%kernel.project_dir%/public/dist/manifest.json"

    http_client:
        scoped_clients:
            amqp.client:
                base_uri: '%env(AMQP_HOST)%'
                auth_basic: '%env(AMQP_MONITORING_USER)%:%env(AMQP_MONITORING_PASSWORD)%'
                headers:
                    Accept: 'application/json'
            heroku.client:
                base_uri:  '%heroku.domain%'
                auth_bearer: '%heroku.api_key%'
                headers:
                    Accept: 'application/vnd.heroku+json; version=3'
                    Content-Type: 'application/json'

when@dev:
    framework:
        assets:
            json_manifest_path: "http://host.docker.internal:9000/dist/manifest.json"
            base_urls:
                - 'http://localhost:9000'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
