parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

imports:
  - { resource: services/app.yaml }
  - { resource: services/tma.yaml }
  - { resource: services/amqp.yaml }